service: yanCuiEcommerce

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: 'eu-west-2'
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants
    - Effect: Allow
      Action: kinesis:PutRecord
      Resource: arn:aws:kinesis:#{AWS::Region}:#{AWS::AccountId}:stream/order-events

functions:
  get-index:
    handler: functions/getIndex.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api_endpoint: https://v3kvmcrg7f.execute-api.eu-west-2.amazonaws.com/dev/restaurants
      orders_api_endpoint: https://v3kvmcrg7f.execute-api.eu-west-2.amazonaws.com/dev/orders
      cognito_user_pool_id: eu-west-2_81YnpSexP
      cognito_client_id: 1ujaun7qpkmqrca0q1ri7ijhvu

  get-restaurants:
    handler: functions/getRestaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: restaurants

  search-restaurants:
    handler: functions/searchRestaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/eu-west-2_81YnpSexP
    environment:
      restaurants_table: restaurants

  place-order:
    handler: functions/placeOrder.handler
    events:
      - http:
          path: /orders
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:#{AWS::Region}:#{AWS::AccountId}:userpool/eu-west-2_81YnpSexP
    environment:
      order_events_stream: order-events

resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    orderEventsStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
